theme = "tokyonight"

editor.soft-wrap.enable = true

editor.cursorcolumn = true
editor.cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.indent-guides]
render = true
character = "|"

[editor.statusline]
left = ["mode", "file-modification-indicator", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "register", "position", "file-type"]
separator = "â”‚"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.whitespace]
render = "all"
